services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_SUPER_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_DATABASE_SCHEMA=${APP_DATABASE_SCHEMA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_SUPER_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:
    name: postgres_data

networks:
  app_network:
    driver: bridge
