# Test-specific settings that override settings.toml when APP_ENV=testing
[default]
# sqlite:///./test.db sqlite://
database_url = "sqlite://"
database_schema = ""
# in-memory, sqlmodel
model_config = "sqlmodel"
migrate_database = false
sqlite_wal_mode = false
env_smoke_test = "configured"
backend_cors_origins = ["http://testserver"]

# You can still use environment-specific overrides in test settings
[development]
env_smoke_test = "development-test"

[production]
env_smoke_test = "production-test"
