[default]
project_name = "python-template"
# dialect+driver://username:password@host:port/database
database_url = "sqlite:///./issues.db"
database_schema = ""
migrate_database = false
sqlite_wal_mode = false
# in-memory, sqlmodel
model_config = "sqlmodel"

# CORS Settings
backend_cors_origins = []
cors_allow_credentials = false
cors_allow_methods = ["*"]
cors_allow_headers = [
  "X-Forwarded-For",
  "Authorization",
  "Content-Type",
  "X-Request-ID",
]
cors_expose_headers = ["X-Process-Time", "X-Request-ID"]

[development]
# Development-specific settings
backend_cors_origins = ["http://localhost:8000", "http://localhost:3000"]

[production]
# Production-specific settings
backend_cors_origins = [] # Set specific origins in production
cors_allow_methods = [
  "GET",
  "POST",
  "PUT",
  "DELETE",
] # Be more restrictive in production

[testing]
# sqlite:///./test.db sqlite://
database_url = "sqlite://"
database_schema = ""
# in-memory, sqlmodel
model_config = "sqlmodel"
migrate_database = false
sqlite_wal_mode = false
backend_cors_origins = ["http://testserver"]
